from .ui_about import Ui_About as Ui_About
from .ui_advance import Ui_Advance as Ui_Advance
from .ui_configs import Ui_Configs as Ui_Configs
from .ui_countdown import Ui_Countdown as Ui_Countdown
from .ui_countdown_custom import Ui_CountdownCustom as Ui_CountdownCustom
from .ui_current_activity import Ui_CurrentActivity as Ui_CurrentActivity
from .ui_custom import Ui_Custom as Ui_Custom
from .ui_exactmenu import Ui_ExactMenu as Ui_ExactMenu
from .ui_next_activity import Ui_NextActivity as Ui_NextActivity
from .ui_preview import Ui_Preview as Ui_Preview
from .ui_schedule_edit import Ui_ScheduleEdit as Ui_ScheduleEdit
from .ui_time import Ui_Time as Ui_Time
from .ui_timeline_edit import Ui_TimelineEdit as Ui_TimelineEdit
from .ui_toast_bar import Ui_ToastBar as Ui_ToastBar
from .ui_weather import Ui_Weather as Ui_Weather
